#!/usr/bin/python3
# library to get arguments
import sys


# fn unpack number factorial
def fc():
    """
    function fc too search file
    """
    try:
        revfile = sys.argv[1]
        with open(revfile) as f:
            for revnumber in f:
                revnumber = int(revnumber)
                if revnumber % 2 == 0:
                        print("{}={}*{}".format(revnumber, revnumber // 2, 2))
                        continue
                w = 3
                while w < revnumber // 2:
                    if revnumber % w == 0:
                        print("{}={}*{}".format(revnumber, revnumber // w, w))
                        break
                    w = w + 2
                if w == (revnumber // 2) + 1:
                    print("{}={}*{}".format(revnumber, revnumber, 1))
    except (IndexError):
        pass


# autostart
fc()
